---
trigger:
- main

pool: NTR

stages:
- stage: image
  jobs:
  - job: imagebuild
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        command: 'buildAndPush'
        Dockerfile: './Dockerfile'
        tags: 'saleor:v1.0'
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'mandhutony'
    command: 'buildAndPush'
    Dockerfile: './Dockerfile'
    tags: 'mandhutony/saleor'