---
trigger:
- main

pool: NTR

stages:
- stage: image
  jobs:
  - job: imagebuild
    steps:
      - task:
        inputs:   
          command: 'buildAndPush'
          Dockerfile: .
          tags: mandhutony/saleor:1.0
           