---
trigger:
- main

pool: NTR

stages:
- stage: image
  jobs:
  - job: imagebuild
    steps:
    - task: Docker@2
      inputs:   
        command: 'buildAndPush'
        Dockerfile: .
        tags: mandhutony/saleor:1.0
